New JFrog Bamboo Plugin
jfrog/bamboo-jfrog-plugin pull request #2
Opened 2023-06-26 13:55 UTC by sverdlov93

2023-06-29 16:59 UTC, yahavi requested changes
Looks very good! Well done! 🥇 

Please consider the following:
1. Run reformat and reorganize import on all files
2. Remove the copyright comment at the top of every Java file
3. Suppress/handle all compiler warnings
4. See my inline comments

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/config/EncryptionHelper.java
> +    private static final String DESEDE_ENCRYPTION_SCHEME = "DESede";
Let's use AES, since DES is no longer considered safe
```suggestion
    private static final String DESEDE_ENCRYPTION_SCHEME = "AES";
```

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/config/EncryptionHelper.java
> +                final byte[] encrypted = new Base32().decode(data);
```suggestion
                final byte[] encrypted = Base32.decode(data);
```

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/config/EncryptionHelper.java
> +    private static ThreadLocal<Cipher> threadLocalEncrypter = new ThreadLocal<Cipher>() {
```suggestion
    private static final ThreadLocal<Cipher> threadLocalEncrypter = ThreadLocal.withInitial(() -> {
```

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/config/EncryptionHelper.java
> +    private static ThreadLocal<Cipher> threadLocalDecrypter = new ThreadLocal<Cipher>() {
```suggestion
    private static final ThreadLocal<Cipher> threadLocalDecrypter = ThreadLocal.withInitial(() -> {
```

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/config/ExistingServersListAction.java
> +	private ServerConfigManager serverConfigManager;
Can be final

2023-06-29 16:59 UTC, yahavi commented on pom.xml
> +            <version>2.14.1</version>
Vulnerabilities
```suggestion
            <version>2.15.2</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.15.2</version>
```

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/JfContext.java
> +        if (!StringUtils.startsWithIgnoreCase(cliCommand.trim(), "jf ")){
1. Don't allow JF
2. cliCommand can be null
3. Fix identation
```suggestion
        if (!StringUtils.startsWith(StringUtils.trim(cliCommand), "jf ")) {
```

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/JfTask.java
> +    public @NotNull TaskResult execute(final @NotNull TaskContext taskContext) throws TaskException {
```suggestion
    public @NotNull TaskResult execute(final @NotNull TaskContext taskContext) {
```

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/JfTask.java
> +    private Map<String, String> createJfrogEnvironmentVariables(BuildContext buildContext, String serverId) throws IOException {
The environment variables should not be overridden if exist. For example, one may like to define a custom JFROG_CLI_BUILD_NAME.

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/JfTask.java
> +        environmentVariables.put("JFROG_CLI_HOME_DIR", BambooUtils.getJfrogSpecificBuildTmp(customVariableContext, fullBuildKey));
Please consider defining JFROG_CLI_ENCRYPTION_KEY if JFROG_CLI_HOME_DIR was not set, to get an extra layer of security.
The value can be as follows:
```java
String key = UUID.randomUUID().toString().replaceAll("-", "");
```

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/config/JfrogServerConfigAction.java
> +                addFieldError("url", "Please specify a valid URL of a JFrog Platform.");
Add the reason
```suggestion
                addFieldError("url", "Please specify a valid URL of a JFrog Platform. " + ExceptionUtils.getRootCauseMessage(mue));
```

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/config/JfrogServerConfigAction.java
> +    public String doAdd() throws Exception {
Is this method in use? If so, please suppress the unused warning
```suggestion
    public String doAdd() {
```
**Same comment for all methods below in this file**

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/config/ServerConfigManager.java
> +        String serverConfigsString = toXMLString(serverConfigs);
Let's use ObjectMapper to serialize/deserialize to JSON and avoid XML.
All methods below can be deleted after this change.

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/utils/BuildLog.java
> + * Wrapper for Jenkins build logger, records log messages from BuildInfo
```suggestion
 * Wrapper for Bamboo build logger, records log messages from BuildInfo
```

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/utils/ExecutableRunner.java
> +}
I think this entire class can be replaced by org.jfrog.build.extractor.executor.CommandExecutor

2023-06-29 16:59 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/utils/OsUtils.java
> +    }
Unused function

2023-06-29 17:28 UTC, sverdlov93 commented on src/main/java/org/jfrog/bamboo/config/JfrogServerConfigAction.java
> +    public String doAdd() throws Exception {
yes

2023-07-04 07:00 UTC, yahavi requested changes

2023-07-18 06:58 UTC, eyalbe4 requested changes
* Added my comments for the documentation changes.
* Since @yahavi is the one who has been reviewing the  plugin code, let's ask him to also review the latest code changes.

2023-07-18 06:58 UTC, eyalbe4 commented on README.md
> +   By setting JFrog CLI version user can make JFrog CLI tasks use a specific JFrog CLI version.
By default, latest JFrog CLI will be used when running JFrog CLI tasks. By setting JFrog CLI version user can make JFrog CLI tasks use a specific JFrog CLI version.
-->
By default, the latest release of JFrog CLI will be installed and used when the JFrog CLI task runs. You can specify a howver a specific version to be used.

2023-07-18 06:58 UTC, eyalbe4 commented on README.md
> +   proxies https://releases.jfrog.io.
By default, JFrog CLI will be downloaded from JFrog's download server - https://releases.jfrog.io/ For users running on air-gaped environments it is possible to download JFrog CLI from the configured JFrog Artifactory. The Source Artifactory Repository should be the name of a Remote/Virtual repository in your Artifactory instance that proxies https://releases.jfrog.io/.
-->
If your Bamboo agents have access to the internet, you can set the JFrog Plugin to download JFrog CLI directly from https://releases.jfrog.io. If not, you can set the plugin to download JFrog CLI through the configured Artifactory instance. Set the Repository Name field value to the name of a Remote or Virtual repository in your Artifactory instance which proxies https://releases.jfrog.io/.

2023-07-23 14:58 UTC, yahavi requested changes
* Let's add `CONTRIBUTING.md` file to explain how to build and test the code

2023-07-23 14:58 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/utils/Utils.java
> +        return str;
I almost sure it does the same (please check me):
```suggestion
        return StringUtils.strip(str, "\"'");
```

2023-07-23 14:58 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/utils/Utils.java
> +            char c = input.charAt(i);
```suggestion
        for (char c : input.toCharArray()) {
```

2023-07-23 14:58 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/utils/Utils.java
> +            if (c == ' ' && !insideDoubleQuotes && !insideSingleQuotes) {
Whitespace can be also tab or a new line
```suggestion
            if (StringUtils.isWhitespace(String.valueOf(c)) && !insideDoubleQuotes && !insideSingleQuotes) {
```

2023-07-23 14:58 UTC, yahavi commented on src/main/java/org/jfrog/bamboo/utils/Utils.java
> +    public static List<String> splitStringPreservingQuotes(String input) {
This function must be checked with an extensive table testing

2023-07-23 14:58 UTC, yahavi commented on .jfrog-pipelines/release/pipelines.release.yml
> +  - name: release_bamboo
```suggestion
  - name: release_jfrog_bamboo
```

2023-07-23 14:58 UTC, yahavi commented on .jfrog-pipelines/release/pipelines.snapshot.yml
> +            # - ./jf am
```suggestion
            - ./jf audit
```

2023-07-23 14:58 UTC, yahavi commented on .jfrog-pipelines/release/pipelines.snapshot.yml
> +            - curl -fL https://getcli.jfrog.io/v2-jf | sh && chmod +x jf
Let's use installCli and replace `./jf` by `jf`

2023-07-31 08:01 UTC, merged